server.port=8466

tomcat.ajp.port=8279

spring.datasource.hikari.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.hikari.jdbc-url=jdbc:log4jdbc:mariadb://dev.in4in.com:3306/coea_web?useUnicode=true&characterEncoding=utf8
spring.datasource.hikari.username=
spring.datasource.hikari.password=

spring.datasource.hikari.connection-timeout=3000
spring.datasource.hikari.max-lifetime=580000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.maximum-pool-size=25

#JWT
jwt.secret.key=DboG3hotIwaWZnzrAhXkhYtEC5iwvQLZ
jwt.subject=coea_token
jwt.issuer=coea
jwt.access.expire.minute=1440

#Etc
op.version=1.0.0
upload.folder=file:/home/webdev/file_upload/Coea/